//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public long Id { get; set; }
        public int ConditionId { get; set; }
        public string GeneralDescription { get; set; }
        public string Description { get; set; }
        public string WeatherIconId { get; set; }
        public double Temperature { get; set; }
        public double Pressure { get; set; }
        public double Humidity { get; set; }
        public double MinTemp { get; set; }
        public double MaxTemp { get; set; }
        public double SeaLevelPressure { get; set; }
        public double GroundLevelPressure { get; set; }
        public double WindSpeed { get; set; }
        public string WindDegrees { get; set; }
        public double Cloudiness { get; set; }
        public System.DateTime CalculationTime { get; set; }
        public System.DateTime Sunrise { get; set; }
        public System.DateTime Sunset { get; set; }
        public long CityId { get; set; }
    
        public virtual City City { get; set; }
    }
}
